version: '2'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --skip-symbolic-links
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schedule
    ports:
      - 3300:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

#  web:
#     build: ./
#     restart: always
#     volumes:
#       - "./web:/home/project"
#     ports:
#         - 3000:3000
#     command: nodemon
